export { authApi } from "./auth";
export { userApi } from "./user";
export { studentApi } from "./student";
export { teacherApi } from "./teacher";
export { financeApi } from "./finance";
export { pdfApi } from "./pdf";
export { curriculumApi } from "./curriculum";
export { examApi } from "./exam";
export { attendanceApi } from "./attendance";
export { meetingApi } from "./meeting";
export { eventApi } from "./event";
export { reportApi } from "./report";
export { activityLogApi } from "./activity";
export { settingsApi } from "./settings";
export { notificationApi } from "./notification";
export { classApi } from "./classApi";
export { achievementApi } from "./achievement";
export { employeeApi } from "./employee";
export { employeeAttendanceApi } from "./employeeAttendance";
export { employeeSalaryApi } from "./employeeSalary";
export { teacherSalaryApi } from "./teacherSalary";
export { studentDocumentsApi } from "./studentDocuments";


export { default as hostelApi } from './hostel';
export { hostelAttendanceApi } from './hostelAttendanceApi';
export { hostelSupervisorApi } from './hostelSupervisorApi';
export { studentTimelineApi } from './studentTimeline';
export { teacherDutiesApi } from './teacherDuties';
export { teacherDocumentsApi } from './teacherDocuments';
export { teacherTimetableApi } from './teacherTimetable';
export { teacherTimelineApi } from './teacherTimeline';
